name: Code style
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: "Setup python"
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - run: pip install requirements-dev.txt
      - run: flake8 hft/src
      - run: isort hft/src --check --diff
      - run: black hft/src --check --diff